### ISSUE TITLE
020875877604963 contains a Luhn sequence

### ISSUE THREAD

**Issue by ieb** [square/luhnybin#4]
I could easily be wrong, ( and often am, its the best way to learn), but my code is identifying a Luhn sequence in nonMatchingSequence(1000) 
The sequence is  020875877604963 and at 15 chars the sequence is a Luhn sequence. The spec says 14 - 16 digits inclusive. 020875877604963 sums to 70. Code pushed to my fork of your repo.

**Comment by ieb** [comment]
Here's a link to the impl https://github.com/ieb/luhnybin/blob/master/luhnywriter/src/main/java/org/apache/people/ieb/luhn/LuhnOutputWriter.java

(license is ASL2, as stated in the pom.xml)

**Comment by ashneyderman** [comment]
this is not luhn sequence. Here is why:

020875877604963

0         0      0
2 \* 2    4      4
0         0      0
8 \* 2  16  -> 7
7                 7

5 \* 2  10  -> 1
8                8
7 \* 2  14      5 
7                 7
6 \* 2   12  -> 3

0                 0 
4 \* 2    8      8
9                 9
6 \* 2    12    3
3                 3

3 + 3 + 9 + 8 + 0 +  -> 23
3 + 7 + 5 + 8 + 1 +  -> 24
7 + 7 + 0 + 4 + 0     -> 18

-> 65 rem 10 = 5

no 70 here.

**Comment by ieb** [comment]
The example given in the ReadMe uses a zero based index. ie

0 \* 2
2
0 \* 2
8
7 \* 2
etc

which gives 70. (just checked it again in a speadsheet)

Your calculation uses a 1 based index making the first number odd, hence not doubled, hence 65.

I dont know which is right, however, code written with a zero based index passes all the earlier tests in the test suite.

I suspect I am wrong since so many others have already provided solutions to the problem, and no one has noticed this.

**Comment by ashneyderman** [comment]
the example of calculations he gives are a bit misleading. He makes it look like he starts counting from the left. Where as description has emphasis on the rightmost digits have to be processed first. So you have to start from the back and then you have to double every second digit. So, in the case of the sequence you have trouble with you start with 36940... and the first digit to double will be 6 then 4, etc. 

I had the same question in comments ... hence I am being so smart :-)

**Comment by ieb** [comment]
Here are both sets, hope Markdown doesnt make a mess of this.

Zero Based index    Number  10s 1s
0   0   0   0
2   2       2
0   0   0   0
8   8       8
7   14  1   4
5   5       5
8   16  1   6
7   7       7
7   14  1   4
6   6       6
0   0   0   0
4   4       4
9   18  1   8
6   6       6
3   6   0   6
            0
    Total   70  

1 Based index  
0   0       0
2   4   0   4
0   0       0
8   16  1   6
7   7       7
5   10  1   0
8   8       8
7   14  1   4
7   7       7
6   12  1   2
0   0       0
4   8   0   8
9   9       9
6   12  1   2
3   3       3
    Total   65

**Comment by ashneyderman** [comment]
yes it is the 1 based index. And I hope it is clear that the index counting is from the back of the sequence. Your earlier tests passing are pure co-incidence.

**Comment by ieb** [comment]
Ahh, that makes sense, thanks for pointing that out.
